name: Review request
on:
  push
jobs:
  review-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            require('./script/reviewRequest.js')({github, context})
